version: '3.1'
services:
  app:
    container_name: teamvoy
    image: teamvoy
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pro100user
      - POSTGRES_DB=shop