spring:
  datasource:
    url: jdbc:postgresql://database:5432/shop
    username: postgres
    password: pro100user
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate:
      default_schema: public
      dialect: org.hibernate.dialect.PostgreSQL91Dialect
    generate-ddl: true
    database: postgresql
    hibernate:
      ddl-auto: update

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

#app
app:
  auth:
    not-auth-endpoints: /login,
                        /registration